# Generated by Django 2.1.5 on 2019-01-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_userprofile_nick_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('s_group_leader', '小组长'), ('b_group_leader', '大组长'), ('administrator', '管理员')], default='小组长', max_length=50, verbose_name='用户类型'),
        ),
    ]
