# Generated by Django 2.1.5 on 2019-01-18 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInformation',
            fields=[
                ('check_category', models.CharField(max_length=30)),
                ('log_level', models.CharField(max_length=15, verbose_name='检查内容')),
                ('information', models.CharField(max_length=100, verbose_name='内容描述')),
                ('detail', models.CharField(max_length=600, verbose_name='详细内容')),
                ('information_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '检查信息',
                'verbose_name_plural': '检查信息',
                'db_table': 'check_information',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EfficiencyStatistic',
            fields=[
                ('statistic_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('number_point', models.IntegerField(verbose_name='采集点数')),
                ('survey_time', models.FloatField(verbose_name='时间段')),
                ('total_time', models.FloatField(blank=True, null=True, verbose_name='总时间')),
            ],
            options={
                'verbose_name': '工作效率',
                'verbose_name_plural': '工作效率',
                'db_table': 'efficiency_statistic',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Surveyattribute',
            fields=[
                ('idsurveyattribute', models.AutoField(db_column='idSurveyAttribute', primary_key=True, serialize=False, verbose_name='ID')),
                ('pjid', models.CharField(db_column='PJID', max_length=50, verbose_name='工程编号')),
                ('pjname', models.CharField(db_column='PJName', max_length=150, verbose_name='工程名称')),
                ('surveyperson', models.CharField(db_column='SurveyPerson', max_length=45, verbose_name='测量员')),
                ('surveytime', models.IntegerField(db_column='SurveyTime', verbose_name='测量时间')),
                ('filetype', models.CharField(db_column='FileType', max_length=45, verbose_name='文件类型')),
                ('isanalysed', models.IntegerField(db_column='IsAnalysed', verbose_name='状态')),
            ],
            options={
                'verbose_name': '工程信息',
                'verbose_name_plural': '工程信息',
                'db_table': 'surveyattribute',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Surveyfile',
            fields=[
                ('idsurveyfile', models.AutoField(db_column='IDsurveyfile', primary_key=True, serialize=False, verbose_name='ID')),
                ('filepath', models.CharField(db_column='FilePath', max_length=300, verbose_name='文件路径')),
                ('ctime', models.DateTimeField(db_column='Ctime', verbose_name='上传时间')),
                ('mtime', models.DateTimeField(db_column='Mtime', verbose_name='建立时间')),
                ('content', models.BinaryField(db_column='Content', verbose_name='文件内容')),
            ],
            options={
                'verbose_name': '文件信息',
                'verbose_name_plural': '文件信息',
                'db_table': 'surveyfile',
                'managed': False,
            },
        ),
    ]
